
###
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "username":"Varu",
    "password": "Nihal",
    "email":"hareesh1@mail.com",
    "profilePic":" "
}

###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email":"hareesh1@mail.com",
    "password": "Nihal"
    
    
}

###
GET http://localhost:4000/api/auth/me
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWY5YWFhMjk4ZWMyZTM4OTk0YjRiMGEiLCJpYXQiOjE3Nzc5NzIxMjksImV4cCI6MTc3ODU3NjkyOX0.-VEoxrpB0RdpPSeXsQmj6enyJSl6KSbLVkh_cM8a7Ko

###
POST http://localhost:4000/api/auth/logout

