###Register User
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "username":"Varu",
    "password": "Nihal",
    "email":"hareesh1@mail.com",
    "profilePic":" "
}

### Login user
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email":"hareesh1@mail.com",
    "password": "Nihal"
    
    
}

### protected route
GET http://localhost:4000/api/auth/me
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWY5YWFhMjk4ZWMyZTM4OTk0YjRiMGEiLCJpYXQiOjE3Nzc5NzIxMjksImV4cCI6MTc3ODU3NjkyOX0.-VEoxrpB0RdpPSeXsQmj6enyJSl6KSbLVkh_cM8a7Ko

### Logout
POST http://localhost:4000/api/auth/logout





# room routes 
### to create room
POST http://localhost:4000/api/room/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWZhY2RiYTM3NWU5ZjMyOWIxMDI4YmYiLCJpYXQiOjE3NzgwNDUyODQsImV4cCI6MTc3ODY1MDA4NH0.WUP5ZqVw8HGoKnIB-Fx2TKeT7JkgtuzDy6s113llZpM; Path=/; HttpOnly; SameSite=Lax

### Room ne fech cheyadaniki, roomid isthe room ne fetch chesthadhi
GET http://localhost:4000/api/room/3a519fd8-f287-4080-bc96-faf9790c274b
# Authorization: yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWZhY2RiYTM3NWU5ZjMyOWIxMDI4YmYiLCJpYXQiOjE3NzgwNDQ2MTQsImV4cCI6MTc3ODY0OTQxNH0._b0yV0ZL_XK0l2fn6FZHQec66IVT9uHeBAfEC50bJcQ; Path=/; HttpOnly; SameSite=Lax


### To get all the rooms of the loged in user
GET http://localhost:4000/api/room/my-rooms
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWZhY2RiYTM3NWU5ZjMyOWIxMDI4YmYiLCJpYXQiOjE3NzgwNDQ4NzYsImV4cCI6MTc3ODY0OTY3Nn0._8XY3QZiDHm3tMnrA9rT30EWJmmLC2Zenzbdd5WkKLw; Path=/; HttpOnly; SameSite=Lax






#code Routes

### get Code 

GET http://localhost:4000/api/code/b6f791fd-8c46-49cb-9eee-ff0ebec60965
#Authorization: Bearer YOUR_TOKEN




###chat routes
GET http://localhost:4000/api/chat/91900c80-4660-42e9-b750-4fb9497f1679